import * as utils from "./utils.js";

export const streetNumberFormatter = val => {
  return val.length>0 ? val : "S/N";
}
export const reverseStreetNumberFormatter = val => {
  return isNaN(parseInt(val)) ? "" : val;
};
export const scheduleFormatter = (daysArr, openArr, closedArr) => { //Takes arrays with all field names and their values; returns a single string containing only days/times selected by the user. Format: "EEEE=HH:mm-HH:mm;". Example: "lunes=08:00-22:30;"
  let scheduleStr = "";
  const days = ["lunes", "martes", "miercoles", "jueves", "viernes", "sabado", "domingo"];
  for (let i=0; i<days.length;i++) {
    let day = days[i];
    let fieldName = days[i] + "Abierto";
    if (daysArr.includes(fieldName)){
      scheduleStr += `${day}=${openArr[i]}-${closedArr[i]};`;
    }
  }
  return scheduleStr;
};
export const reverseScheduleFormatter = str => { //Takes a string generated by scheduleFormatter(); returns a 1-level object with schedule fields for every day/time (24h-format), even those not selected by the user.
  const scheduleObj = {};
  const openDays = str.split(/;|=/).filter(e => e.indexOf(":") == -1 && e.length > 0);
  const openTimes = str.split(/-|=/).filter(e => e.indexOf(";") == -1 && e.indexOf(":") != -1);
  const closingTimes = str.split(/-|;/).filter(e => e.indexOf("=") == -1 && e.indexOf(":") != -1);
  const days = ["lunes", "martes", "miercoles", "jueves", "viernes", "sabado", "domingo"];
  while (days.length > 0){
    let day = days.shift();
    scheduleObj[day + "Abierto"] = openDays.includes(day) ? "on" : "off";
    scheduleObj["apertura" + utils.capitalize(day)] = openDays.includes(day) ? openTimes.shift() : "08:00";
    scheduleObj["cierre" + utils.capitalize(day)] = openDays.includes(day) ? closingTimes.shift() : "22:30";
    }
  return scheduleObj;
};
export const checkInOutFormatter = (checkIn, checkOut) => {//Takes two string values containing the check-in/check-out times; returns a single string with both times in 24h-format. Format: "in=HH:mm;out=HH:mm". Example: "in=15:00;out=12:00".
  return `in=${checkIn};out=${checkOut}`;
};
export const reverseCheckInOutFormatter = str => {//Takes a string generated by checkInOutFormatter(); returns an object with check-ib/check-out times. Format: {}
  const vals = str.split(/=|;/).filter(e => e.indexOf(":") != -1);;
  return {checkIn:vals[0], checkOut:vals[1]};
};
